name: Digital CV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run pre-deploy script
        run: |
          chmod +x ./minify.sh
          bash ./minify.sh